//! Stamp release builds once; ordinary Cargo builds remain local and never
//! self-update. Also generates the embedded documentation table from `docs/`,
//! so the guides have one source: the files themselves.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    for key in ["E_BUILD_VERSION", "E_BUILD_COMMIT", "E_BUILD_CHANNEL"] {
        println!("cargo:rerun-if-env-changed={key}");
    }
    let version =
        std::env::var("E_BUILD_VERSION").unwrap_or_else(|_| env!("CARGO_PKG_VERSION").to_owned());
    let channel = std::env::var("E_BUILD_CHANNEL").unwrap_or_else(|_| "local".into());
    assert!(["local", "stable", "dev", "beta", "pr"].contains(&channel.as_str()));
    if channel == "stable" {
        assert_eq!(
            version,
            env!("CARGO_PKG_VERSION"),
            "stable version must match Cargo.toml"
        );
    } else if channel != "local" {
        assert!(
            version.starts_with(&format!("{}-{channel}.", env!("CARGO_PKG_VERSION"))),
            "preview identity must match manifest and channel"
        );
    }
    let commit = std::env::var("E_BUILD_COMMIT").unwrap_or_else(|_| "local".into());
    assert!(version
        .bytes()
        .all(|c| c.is_ascii_alphanumeric() || b".-".contains(&c)));
    assert!(
        commit == "local" || (commit.len() == 40 && commit.bytes().all(|c| c.is_ascii_hexdigit()))
    );
    println!("cargo:rustc-env=E_VERSION={version}");
    println!("cargo:rustc-env=E_CHANNEL={channel}");
    println!("cargo:rustc-env=E_COMMIT={commit}");

    generate_docs();
}

/// One row of the embedded documentation table.
struct Guide {
    group: u32,
    order: u32,
    topic: String,
    blurb: String,
    path: PathBuf,
}

/// Generate `TOPICS` and `body()` for `e docs` by reading `docs/`: the folder
/// is the nav group (`NN-name`), the file stem is the topic, and front matter
/// carries `title`, `description`, and `order`. The website reads the same
/// files, so there is no second list of topics to keep in step.
fn generate_docs() {
    let docs = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("docs");
    println!("cargo:rerun-if-changed={}", docs.display());

    let mut guides: Vec<Guide> = Vec::new();
    for group in entries(&docs) {
        if !group.is_dir() {
            continue;
        }
        let group_order = group_order(&group);
        for file in entries(&group) {
            // A folder's README.md is repository metadata: it names the group
            // and orders it, and it is never a topic or a page.
            if file.extension().is_none_or(|ext| ext != "md")
                || file.file_name().is_some_and(|name| name == "README.md")
            {
                continue;
            }
            let topic = file.file_stem().unwrap().to_string_lossy().into_owned();
            let text = std::fs::read_to_string(&file)
                .unwrap_or_else(|error| panic!("cannot read {}: {error}", file.display()));
            let (description, order) = front_matter(&text).unwrap_or_else(|| {
                panic!(
                    "{} has no front matter: add title, description, and order",
                    file.display()
                )
            });
            guides.push(Guide {
                group: group_order,
                order,
                topic,
                blurb: description,
                path: file,
            });
        }
    }
    guides.sort_by(|left, right| {
        (left.group, left.order, &left.topic).cmp(&(right.group, right.order, &right.topic))
    });

    let mut source = String::from("// Generated by build.rs from docs/ — do not edit.\n\n");
    source.push_str("pub const TOPICS: &[(&str, &str)] = &[\n");
    for guide in &guides {
        writeln!(source, "    ({:?}, {:?}),", guide.topic, guide.blurb).unwrap();
    }
    source
        .push_str("];\n\npub fn body(topic: &str) -> Option<&'static str> {\n    match topic {\n");
    for guide in &guides {
        writeln!(
            source,
            "        {:?} => Some(include_str!({:?})),",
            guide.topic,
            guide.path.display().to_string()
        )
        .unwrap();
    }
    source.push_str("        _ => None,\n    }\n}\n");
    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("docs.rs");
    std::fs::write(&out, source)
        .unwrap_or_else(|error| panic!("cannot write {}: {error}", out.display()));
}

/// The front matter's `description` and `order`; `title` is the website's label,
/// which the binary has no use for but every guide must carry.
fn front_matter(text: &str) -> Option<(String, u32)> {
    let mut lines = text.lines();
    if lines.next()?.trim_end() != "---" {
        return None;
    }
    let (mut description, mut order) = (None, None);
    for line in lines {
        if line.trim_end() == "---" {
            break;
        }
        let (key, value) = line.split_once(':')?;
        match key.trim() {
            "description" => description = Some(value.trim().to_string()),
            "title" if value.trim().is_empty() => return None,
            "order" => order = value.trim().parse().ok(),
            _ => {}
        }
    }
    Some((description?, order.unwrap_or(999)))
}

/// Directory entries, sorted, skipping nothing: the caller decides.
fn entries(dir: &Path) -> Vec<PathBuf> {
    let mut found: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|error| panic!("cannot read {}: {error}", dir.display()))
        .map(|entry| entry.unwrap().path())
        .collect();
    found.sort();
    found
}

/// A group's order comes from its own README.md. The folder is the group's
/// name on the website, so nothing about it is numbered.
fn group_order(group: &Path) -> u32 {
    let readme = group.join("README.md");
    let text = std::fs::read_to_string(&readme).unwrap_or_else(|error| {
        panic!(
            "{} needs a README.md with title, description, and order front matter: {error}",
            group.display()
        )
    });
    let (_, order) =
        front_matter(&text).unwrap_or_else(|| panic!("{} has no front matter", readme.display()));
    order
}
